### ISSUE TITLE
Missing multiplier for /MCL

### ISSUE THREAD

**Issue by def-mycroft** [beancount/johnny#11]
I get this `KeyError` when running johnny-import:

```
  File "/home/dasenbrj/code_repos/johnny/johnny/johnny/sources/tastyworks_csv/symbols.py", line 82, in _ParseFuturesSymbol
    multiplier = multipliers.MULTIPLIERS[underlying[:-3]]
KeyError: '/MCL'
```

**Comment by def-mycroft** [comment]
actually this is a `mulmat` issue

**Comment by blais** [comment]
You trade too small! use /CL
Just kidding, will update mulmat now

**Comment by def-mycroft** [comment]
haha, very nice @blais . 

also missing multiplier for /MBT and /BTC on CME

**Comment by blais** [comment]
Send me the multipliers

**Comment by nicola** [comment]
is there a discord where I can ask some questions?

**Comment by blais** [comment]
No discord. I don't use it. Send me email or file an issue like this.
