### ISSUE TITLE
`setup.py not found` 

### ISSUE THREAD

**Issue by def-mycroft** [beancount/johnny#9]
The README mentions using command `pip install --editable .` under heading "Setting up Johnny in a virtual environment", however this does not work: 

```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: <path to johnny source dir> 
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by Graeme22** [comment]
There's a `setup.cfg` which should work, you're probably not running the command in the top level directory

**Comment by def-mycroft** [comment]
I'm running it in the same directory as the `setup.cfg` file.

**Comment by dnicolodi** [comment]
The presence of the `pyproject.toml` file makes pip to attempt to install the package in "PEP517" mode, which does not yet support editable install mode. If you don't want to hack on Johnny itself, simply drop the `--editable` flag. If you want and editable install, remove the `pyproject.toml` and try again. Another work-around is to add a `setup.py` file with this content
```
import setuptools
setuptools.setup()
```
and install in editable mode with `python setup.py install --editable`.

**Comment by def-mycroft** [comment]
thanks @dnicolodi , that is helpful. I'll edited the README later and submit a pr.

**Comment by blais** [comment]
I have no idea I didn't create this setup.
I don't understand how it works, --editable creates a directory that doesn't include the target, doesn't make any sense to me.

I'll let you figure it out or delete all this stuff and just have a good old setup.py

**Comment by blais** [comment]
Oh it looks like it's some newfangled thing.
What a mess Python packaging has become.

Don't install like that; just setup your PYTHONPATH and PATH to pick up the code directly and move on.
Your life will be much easier, and you can regularly update the repo with a simple git pull.
